import { Conversation, SharedMessage, SharedSnapshotData } from "./types";

// Maximum URL length safely supported across all browsers, proxies, and platforms
export const MAX_SAFE_URL_LENGTH = 2800;

// Maximum message turns to include in a frontend link snapshot
export const MAX_SNAPSHOT_MESSAGES = 20;

// Maximum character length per individual message content
export const MAX_MESSAGE_CHAR_LENGTH = 2500;

interface SnapshotPayload {
  v: 1;
  t: string;
  top?: string;
  m: Array<{
    r: "u" | "a";
    c: string;
  }>;
}

/**
 * Encodes a Uint8Array to a URL-safe Base64 string (no +, /, or =).
 */
export function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

/**
 * Decodes a URL-safe Base64 string back into a Uint8Array.
 */
export function base64UrlToUint8Array(base64url: string): Uint8Array {
  let base64 = base64url.replace(/-/g, "+").replace(/_/g, "/");
  while (base64.length % 4) {
    base64 += "=";
  }
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Compresses a UTF-8 string using deflate-raw via CompressionStream if available,
 * falling back to direct base64url encoding.
 */
async function compressSnapshotString(text: string): Promise<string> {
  const textBytes = new TextEncoder().encode(text);

  if (typeof CompressionStream !== "undefined") {
    try {
      const cs = new CompressionStream("deflate-raw");
      const writer = cs.writable.getWriter();
      writer.write(textBytes as unknown as BufferSource);
      writer.close();

      const reader = cs.readable.getReader();
      const chunks: Uint8Array[] = [];
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        if (value) chunks.push(value);
      }

      let totalLen = chunks.reduce((acc, c) => acc + c.length, 0);
      let merged = new Uint8Array(totalLen);
      let offset = 0;
      for (const c of chunks) {
        merged.set(c, offset);
        offset += c.length;
      }

      return "df." + uint8ArrayToBase64Url(merged);
    } catch {
      // If CompressionStream fails, fall through to base64url fallback
    }
  }

  return "b64." + uint8ArrayToBase64Url(textBytes);
}

/**
 * Decompresses and decodes a token generated by compressSnapshotString.
 */
async function decompressSnapshotString(token: string): Promise<string | null> {
  try {
    if (token.startsWith("df.")) {
      const raw = base64UrlToUint8Array(token.slice(3));
      if (typeof DecompressionStream !== "undefined") {
        const ds = new DecompressionStream("deflate-raw");
        const writer = ds.writable.getWriter();
        writer.write(raw as unknown as BufferSource);
        writer.close();

        const reader = ds.readable.getReader();
        const chunks: Uint8Array[] = [];
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          if (value) chunks.push(value);
        }

        let totalLen = chunks.reduce((acc, c) => acc + c.length, 0);
        let merged = new Uint8Array(totalLen);
        let offset = 0;
        for (const c of chunks) {
          merged.set(c, offset);
          offset += c.length;
        }

        return new TextDecoder().decode(merged);
      }
    }

    if (token.startsWith("b64.")) {
      const raw = base64UrlToUint8Array(token.slice(4));
      return new TextDecoder().decode(raw);
    }

    // Direct fallback for un-prefixed base64url
    const raw = base64UrlToUint8Array(token);
    return new TextDecoder().decode(raw);
  } catch {
    return null;
  }
}

/**
 * Extracts clean, sanitized user/assistant message pairs from an active conversation.
 * Excludes transient errors, raw graph state, and any private state.
 */
export function extractSharedMessages(conversation: Conversation | null): SharedMessage[] {
  if (!conversation || !conversation.messages) return [];
  const result: SharedMessage[] = [];
  for (const msg of conversation.messages) {
    if (msg.query && msg.query.trim()) {
      result.push({
        role: "user",
        content: msg.query.trim().slice(0, MAX_MESSAGE_CHAR_LENGTH),
        topic: msg.response?.topic || null,
      });
    }
    if (msg.response?.answer && msg.response.answer.trim()) {
      result.push({
        role: "assistant",
        content: msg.response.answer.trim().slice(0, MAX_MESSAGE_CHAR_LENGTH),
        topic: msg.response?.topic || null,
      });
    }
  }
  return result.slice(0, MAX_SNAPSHOT_MESSAGES);
}

export interface ConversationPreviewData {
  hasContent: boolean;
  title: string;
  topic?: string | null;
  firstQuestion?: string;
  firstAnswerPreview?: string;
  messageCount: number;
}

export interface PreparedShareData {
  title: string;
  text: string;
  url: string;
  preview: ConversationPreviewData;
}

/**
 * Strips markdown symbols (headers, bold/italic, links, hr rules) so text
 * renders cleanly inside compact dialog previews without raw markup.
 */
function cleanPreviewText(text: string): string {
  return text
    .replace(/^[ \t]*([-*_=])(?:[ \t]*\1){2,}[ \t]*$/gm, " ")
    .replace(/^[ \t]*#{1,6}[ \t]+/gm, "")
    .replace(/^[ \t]*[-*+•][ \t]+/gm, "")
    .replace(/^[ \t]*>[ \t]?/gm, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[`*_~]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Truncates text safely at word boundary with an ellipsis.
 */
function truncateText(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  const sub = text.slice(0, maxLength);
  const lastSpace = sub.lastIndexOf(" ");
  return (lastSpace > 0 ? sub.slice(0, lastSpace) : sub).trim() + "…";
}

/**
 * Prepares privacy-preserving preview data for the Share dialog.
 */
export function prepareShareData(conversation: Conversation | null): PreparedShareData {
  const safeBase =
    typeof window !== "undefined"
      ? window.location.origin
      : "https://edu-graph-ai.vercel.app";

  if (!conversation || !conversation.messages || conversation.messages.length === 0) {
    return {
      title: "EduGraphAI — Knowledge Graph Learning Assistant",
      text: "Explore academic concepts with EduGraphAI, an AI-powered Knowledge Graph learning assistant.",
      url: safeBase,
      preview: {
        hasContent: false,
        title: conversation?.title || "New Chat",
        messageCount: 0,
      },
    };
  }

  // Find the first meaningful user query in the conversation
  const firstMsg =
    conversation.messages.find((m) => m.query && m.query.trim().length > 0) ||
    conversation.messages[0];

  const firstQuestion = firstMsg?.query?.trim() || "";
  const rawAnswer = firstMsg?.response?.answer || "";
  const cleanAnswer = cleanPreviewText(rawAnswer);
  const firstAnswerPreview = cleanAnswer ? truncateText(cleanAnswer, 180) : undefined;
  const topic = firstMsg?.response?.topic || null;

  const displayTitle =
    conversation.title && conversation.title !== "New Chat"
      ? `${conversation.title} | EduGraphAI`
      : topic
      ? `${topic} | EduGraphAI`
      : "EduGraphAI — Knowledge Graph Learning Assistant";

  const shareText = firstQuestion
    ? `Learning discussion on "${truncateText(firstQuestion, 60)}" via EduGraphAI`
    : "Explore academic topics with EduGraphAI Knowledge Graph Learning Assistant";

  return {
    title: displayTitle,
    text: shareText,
    url: safeBase,
    preview: {
      hasContent: true,
      title: conversation.title || "Conversation",
      topic,
      firstQuestion: truncateText(firstQuestion, 120),
      firstAnswerPreview,
      messageCount: conversation.messages.length,
    },
  };
}

export interface EncodeSnapshotResult {
  url: string;
  token: string;
  isOversized: boolean;
  errorMessage?: string;
}

/**
 * Encodes the active conversation into a frontend-only URL snapshot.
 * Enforces size limits to prevent broken or untransmittable URLs.
 */
export async function encodeConversationSnapshot(
  conversation: Conversation | null,
  originUrl?: string
): Promise<EncodeSnapshotResult> {
  const baseUrl =
    originUrl ||
    (typeof window !== "undefined"
      ? window.location.origin
      : "https://edu-graph-ai.vercel.app");

  const messages = extractSharedMessages(conversation);
  if (messages.length === 0) {
    return {
      url: baseUrl,
      token: "",
      isOversized: false,
    };
  }

  const firstMsg = conversation?.messages?.[0];
  const topic =
    conversation?.messages.find((m) => m.response?.topic)?.response?.topic ||
    firstMsg?.response?.topic ||
    undefined;

  const title =
    conversation?.title && conversation.title !== "New Chat"
      ? conversation.title.slice(0, 100)
      : firstMsg?.query
      ? firstMsg.query.slice(0, 80)
      : "EduGraphAI Conversation";

  const payload: SnapshotPayload = {
    v: 1,
    t: title,
    top: topic ? topic.slice(0, 60) : undefined,
    m: messages.map((m) => ({
      r: m.role === "user" ? "u" : "a",
      c: m.content,
    })),
  };

  const jsonString = JSON.stringify(payload);
  const token = await compressSnapshotString(jsonString);
  const fullUrl = `${baseUrl.replace(/\/+$/, "")}/share/${token}`;

  if (fullUrl.length > MAX_SAFE_URL_LENGTH) {
    return {
      url: "",
      token: "",
      isOversized: true,
      errorMessage:
        "This conversation is too large to share as a link. Start a shorter conversation or copy the important part manually.",
    };
  }

  return {
    url: fullUrl,
    token,
    isOversized: false,
  };
}

/**
 * Decodes and validates a frontend snapshot token from the URL.
 * Returns null if the token is invalid, corrupted, or unsupported.
 */
export async function decodeConversationSnapshot(
  token: string
): Promise<SharedSnapshotData | null> {
  if (!token || typeof token !== "string") return null;

  try {
    const rawJson = await decompressSnapshotString(token.trim());
    if (!rawJson) return null;

    const parsed = JSON.parse(rawJson);
    if (!parsed || parsed.v !== 1 || typeof parsed.t !== "string" || !Array.isArray(parsed.m)) {
      return null;
    }

    const messages: SharedMessage[] = [];
    for (const item of parsed.m) {
      if (
        item &&
        (item.r === "u" || item.r === "a") &&
        typeof item.c === "string" &&
        item.c.trim().length > 0
      ) {
        messages.push({
          role: item.r === "u" ? "user" : "assistant",
          content: item.c,
          topic: parsed.top || null,
        });
      }
    }

    if (messages.length === 0) return null;

    return {
      title: parsed.t || "EduGraphAI Conversation",
      topic: parsed.top || null,
      messages,
    };
  } catch {
    return null;
  }
}

/**
 * Copies the share URL to the system clipboard.
 */
export async function copyShareLink(url: string): Promise<boolean> {
  if (
    typeof navigator !== "undefined" &&
    navigator.clipboard &&
    typeof navigator.clipboard.writeText === "function"
  ) {
    try {
      await navigator.clipboard.writeText(url);
      return true;
    } catch {
      return false;
    }
  }
  return false;
}

/**
 * Checks if native Web Share is supported in the current environment.
 */
export function isNativeShareSupported(): boolean {
  return typeof navigator !== "undefined" && typeof navigator.share === "function";
}

/**
 * Triggers native Web Share if supported. Handles user cancellation (AbortError) silently.
 */
export async function triggerNativeShare(data: {
  title: string;
  text?: string;
  url: string;
}): Promise<"shared" | "aborted" | "unsupported" | "error"> {
  if (!isNativeShareSupported()) return "unsupported";
  try {
    if (typeof navigator.canShare === "function" && !navigator.canShare(data)) {
      return "unsupported";
    }
    await navigator.share(data);
    return "shared";
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") {
      return "aborted";
    }
    return "error";
  }
}
